apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-auth-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
        - name: 'app'
          image: 'app'
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: app-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
